spring:
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/loja
    username: root
    password: gust
    driver-class-name: com.mysql.cj.jdbc.Driver
